sudo: required

services:
  - docker

language: node_js

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - export REPO=denniseffing/mts-dishes
  - export REPO_INIT=denniseffing/mts-dishes-dynamo-init
  - export TAG=`if [ -n "$TRAVIS_TAG" ]; then echo $TRAVIS_TAG; else echo "nightly" ; fi`
  - docker build -f Dockerfile -t $REPO:$TAG .
  - docker build -f src/database/Dockerfile -t $REPO_INIT:$TAG .
  - docker push $REPO
  - docker push $REPO_INIT
